sudo: required

services:
- docker

addons:
  apt:
    packages:
      - docker-ce
      - curl
install: skip

jobs:
  include:
    - &deploy-stage
      stage: build and deploy
      script:
        - curl -L -O $QEMU_BIN_URI
        - chmod 755 qemu-arm-static
        # build
        - docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f Dockerfile .
        # test
        #- docker run --rm --privileged multiarch/qemu-user-static:register --reset
      after_success:
        - |
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
          docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_USER/$DOCKER_IMAGE:$DOCKER_TAG
          docker push $DOCKER_USER/$DOCKER_IMAGE:$DOCKER_TAG
      env:
        - DOCKER_TAG=armhf
        - QEMU_BIN_URI='https://github.com/multiarch/qemu-user-static/releases/download/v4.1.0-1/qemu-arm-static'
env:
  global:
  - DOCKER_IMAGE=armhf-alpine-qemu
